spring:
  application:
    name: minimal-ecommerce-backend-api
  datasource:
    url: jdbc:postgresql://localhost:5432/minimal_ecommerce_db
    username: postgres
    password: mannu@scaler
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
